// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuMfhRQYOY9qEyhCdCnFBr_BzY7DlfpgM',
    appId: '1:84544124024:web:2a5b7201f379ec453f698d',
    messagingSenderId: '84544124024',
    projectId: 'groovroads01-b1f7c',
    authDomain: 'groovroads01-b1f7c.firebaseapp.com',
    storageBucket: 'groovroads01-b1f7c.firebasestorage.app',
    measurementId: 'G-PZYSS3LSFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMm0ri86b1t6WENGcmuYtgfLAKICS7cY',
    appId: '1:84544124024:android:f1e0e8a81dcb53233f698d',
    messagingSenderId: '84544124024',
    projectId: 'groovroads01-b1f7c',
    storageBucket: 'groovroads01-b1f7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCllXeTVlb0lHcJh89ZqhMyNkdB0YkPyg0',
    appId: '1:84544124024:ios:ad0e5592756cffbb3f698d',
    messagingSenderId: '84544124024',
    projectId: 'groovroads01-b1f7c',
    storageBucket: 'groovroads01-b1f7c.firebasestorage.app',
    iosBundleId: 'com.example.groovroads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCllXeTVlb0lHcJh89ZqhMyNkdB0YkPyg0',
    appId: '1:84544124024:ios:ad0e5592756cffbb3f698d',
    messagingSenderId: '84544124024',
    projectId: 'groovroads01-b1f7c',
    storageBucket: 'groovroads01-b1f7c.firebasestorage.app',
    iosBundleId: 'com.example.groovroads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuMfhRQYOY9qEyhCdCnFBr_BzY7DlfpgM',
    appId: '1:84544124024:web:6808dad79c2daddc3f698d',
    messagingSenderId: '84544124024',
    projectId: 'groovroads01-b1f7c',
    authDomain: 'groovroads01-b1f7c.firebaseapp.com',
    storageBucket: 'groovroads01-b1f7c.firebasestorage.app',
    measurementId: 'G-18JS338XZH',
  );
}
